source "https://rubygems.org"

ruby "2.1.5"

gem "lita"
gem "lita-slack"

gem "lita-google-images"
gem "lita-karma"
gem "lita-slack-karma-sync"
gem "lita-catgif"
gem "lita-catfacts"
gem "lita-cowsay"
gem "lita-excuses"
gem "lita-fortune"
gem "lita-shipit"
gem "lita-flip"
gem "lita-giphy"
gem "lita-pugbomb"
gem "lita-y"
gem "lita-rules"
gem "lita-high-five"
gem "lita-applause"
